HTMLArea.AboutEditor=HTMLArea.Plugin.extend({constructor:function(editor,pluginName){this.base(editor,pluginName);},configurePlugin:function(editor){var pluginInformation={version:'2.0',developer:'Stanislas Rolland',developerUrl:'http://www.sjbr.ca/',copyrightOwner:'Stanislas Rolland',sponsor:'SJBR',sponsorUrl:'http://www.sjbr.ca/',license:'GPL'};this.registerPluginInformation(pluginInformation);var buttonId='About';var buttonConfiguration={id:buttonId,tooltip:this.localize(buttonId.toLowerCase()),action:'onButtonPress',textMode:true,dialog:true,iconCls:'htmlarea-action-editor-show-about'};this.registerButton(buttonConfiguration);return true;},browsers:['Firefox 1.5+','Google Chrome 1.0+','Internet Explorer 6.0+','Opera 9.62+','Safari 3.0.4+','SeaMonkey 1.0+'],onButtonPress:function(editor,id){var buttonId=this.translateHotKey(id);buttonId=buttonId?buttonId:id;this.openDialogue(buttonId,'About HTMLArea',this.getWindowDimensions({width:450,height:350},buttonId),this.buildTabItems());return false;},openDialogue:function(buttonId,title,dimensions,tabItems){this.dialog=new Ext.Window({title:this.localize(title),cls:'htmlarea-window',border:false,width:dimensions.width,height:'auto',resizable:!Ext.isIE,iconCls:this.getButton(buttonId).iconCls,listeners:{close:{fn:this.onClose,scope:this}},items:{xtype:'tabpanel',activeTab:0,listeners:{activate:{fn:this.resetFocus,scope:this},tabchange:{fn:this.syncHeight,scope:this}},items:tabItems},buttons:[this.buildButtonConfig('Close',this.onCancel)]});this.show();},buildTabItems:function(){var tabItems=[];tabItems.push({xtype:'panel',cls:'about',title:this.localize('About'),html:'<h1 id="version">htmlArea RTE '+RTEarea[0].version+'</h1>'
+'<p>'+this.localize('free_editor').replace('<','&lt;').replace('>','&gt;')+'</p>'
+'<p><br />'+this.localize('Browser support')+': '+this.browsers.join(', ')+'.</p>'
+'<p><br />'+this.localize('product_documentation')+'&nbsp;<a href="http://typo3.org/extensions/repository/view/rtehtmlarea_manual/current/">typo3.org</a></p>'
+'<p style="text-align: center;">'
+'<br />'
+'&copy; 2002-2004 <a href="http://interactivetools.com" target="_blank">interactivetools.com, inc.</a><br />'
+'&copy; 2003-2004 <a href="http://dynarch.com" target="_blank">dynarch.com LLC.</a><br />'
+'&copy; 2004-2010 <a href="http://www.sjbr.ca" target="_blank">Stanislas Rolland</a><br />'
+this.localize('All rights reserved.')
+'</p>'});if(!this.store){this.store=new Ext.data.ArrayStore({fields:[{name:'name'},{name:'developer'},{name:'sponsor'}],sortInfo:{field:'name',direction:'ASC'},data:this.getPluginsInfo()});}
tabItems.push({xtype:'panel',cls:'about-plugins',height:200,title:this.localize('Plugins'),autoScroll:true,items:{xtype:'listview',store:this.store,reserveScrollOffset:true,columns:[{header:this.localize('Name'),dataIndex:'name',width:.33},{header:this.localize('Developer'),dataIndex:'developer',width:.33},{header:this.localize('Sponsored by'),dataIndex:'sponsor'}]}});return tabItems;},getPluginsInfo:function(){var pluginsInfo=[];Ext.iterate(this.editor.plugins,function(pluginId,plugin){pluginsInfo.push([plugin.name+' '+plugin.version,'<a href="'+plugin.developer_url+'" target="_blank">'+plugin.developer+'</a>','<a href="'+plugin.sponsor_url+'" target="_blank">'+plugin.sponsor+'</a>']);},this);return pluginsInfo;}});