HTMLArea.Editor.prototype.isEditable=function(){return(this._doc.designMode==="on");};HTMLArea.Editor.prototype._getSelection=function(){return this._iframe.contentWindow.getSelection();};HTMLArea.Editor.prototype.emptySelection=function(selection){if(Ext.isWebKit){if(Ext.isFunction(selection.removeAllRanges)){selection.removeAllRanges();}else{selection.empty();}}else{selection.removeAllRanges();}
if(Ext.isOpera){this.focus();}};HTMLArea.Editor.prototype.addRangeToSelection=function(selection,range){if(Ext.isWebKit){if(Ext.isFunction(selection.addRange)){selection.addRange(range);}else{selection.setBaseAndExtent(range.startContainer,range.startOffset,range.endContainer,range.endOffset);}}else{selection.addRange(range);}};HTMLArea.Editor.prototype._createRange=function(sel){if(Ext.isEmpty(sel)){return this._doc.createRange();}
if(Ext.isWebKit&&!sel.getRangeAt){var range=this._doc.createRange();if(typeof(sel)=="undefined"){return range;}else if(sel.baseNode==null){range.setStart(this._doc.body,0);range.setEnd(this._doc.body,0);return range;}else{range.setStart(sel.baseNode,sel.baseOffset);range.setEnd(sel.extentNode,sel.extentOffset);if(range.collapsed!=sel.isCollapsed){range.setStart(sel.extentNode,sel.extentOffset);range.setEnd(sel.baseNode,sel.baseOffset);}
return range;}}
try{return sel.getRangeAt(0);}catch(e){return this._doc.createRange();}};HTMLArea.Editor.prototype.selectNode=function(node,endPoint){this.focus();var selection=this._getSelection();if(Ext.isWebKit&&/^(img)$/i.test(node.nodeName)){this._getSelection().setBaseAndExtent(node,0,node,1);}else{var range=this._doc.createRange();if(node.nodeType==1&&node.nodeName.toLowerCase()=="body"){if(Ext.isWebKit){range.setStart(node,0);range.setEnd(node,node.childNodes.length);}else{range.selectNodeContents(node);}}else{range.selectNode(node);}
if(typeof(endPoint)!="undefined"){range.collapse(endPoint);}
this.emptySelection(selection);this.addRangeToSelection(selection,range);}};HTMLArea.Editor.prototype.selectNodeContents=function(node,endPoint){this.focus();var selection=this._getSelection();var range=this._doc.createRange();if(Ext.isWebKit){range.setStart(node,0);if(node.nodeType==3||node.nodeType==8||node.nodeType==4){range.setEnd(node,node.textContent.length);}else{range.setEnd(node,node.childNodes.length);}}else{range.selectNodeContents(node);}
if(typeof(endPoint)!=="undefined"){range.collapse(endPoint);}
this.emptySelection(selection);this.addRangeToSelection(selection,range);};HTMLArea.Editor.prototype.rangeIntersectsNode=function(range,node){var nodeRange=this._doc.createRange();try{nodeRange.selectNode(node);}catch(e){if(Ext.isWebKit){nodeRange.setStart(node,0);if(node.nodeType==3||node.nodeType==8||node.nodeType==4){nodeRange.setEnd(node,node.textContent.length);}else{nodeRange.setEnd(node,node.childNodes.length);}}else{nodeRange.selectNodeContents(node);}}
return(range.compareBoundaryPoints(range.END_TO_START,nodeRange)==-1&&range.compareBoundaryPoints(range.START_TO_END,nodeRange)==1)||(range.compareBoundaryPoints(range.END_TO_START,nodeRange)==1&&range.compareBoundaryPoints(range.START_TO_END,nodeRange)==-1);};HTMLArea.Editor.prototype.getSelectionType=function(selection){var type='Text';if(!selection){var selection=this._getSelection();}
if(selection&&selection.rangeCount==1){var range=selection.getRangeAt(0);if(range.startContainer.nodeType==1){if((range.startContainer==range.endContainer&&(range.endOffset-range.startOffset)==1)||(range.endContainer.nodeType==3&&range.endOffset==0&&range.startContainer.childNodes[range.startOffset].nextSibling==range.endContainer)){if(/^(img|hr|li|table|tr|td|embed|object|ol|ul|dl)$/i.test(range.startContainer.childNodes[range.startOffset].nodeName)){type='Control';}}}}
return type;};HTMLArea.Editor.prototype.getSelectionRanges=function(selection){if(!selection){var selection=this._getSelection();}
var ranges=[];if(selection.getRangeAt){for(var i=selection.rangeCount;--i>=0;){ranges.push(selection.getRangeAt(i));}}
return ranges;};HTMLArea.Editor.prototype.setSelectionRanges=function(ranges,selection){if(!selection){var selection=this._getSelection();}
if(selection.getRangeAt){this.emptySelection(selection);for(var i=ranges.length;--i>=0;){this.addRangeToSelection(selection,ranges[i]);}}};HTMLArea.Editor.prototype.getSelectedElement=function(selection){var selectedElement=null;if(!selection){var selection=this._getSelection();}
if(selection&&selection.anchorNode&&selection.anchorNode.nodeType==1){if(this.getSelectionType(selection)=="Control"){selectedElement=selection.anchorNode.childNodes[selection.anchorOffset];if(!selectedElement){selectedElement=selection.anchorNode;}else if(selectedElement.nodeType!=1){return null;}}}
return selectedElement;};HTMLArea.Editor.prototype.getSelectedHTML=function(){var range=this._createRange(this._getSelection());if(range.collapsed)return"";var cloneContents=range.cloneContents();if(!cloneContents){cloneContents=this._doc.createDocumentFragment();}
return HTMLArea.getHTML(cloneContents,false,this);};HTMLArea.Editor.prototype.getSelectedHTMLContents=function(){return this.getSelectedHTML();};HTMLArea.Editor.prototype.getParentElement=function(selection,range){if(!selection){var selection=this._getSelection();}
if(this.getSelectionType(selection)==="Control"){return this.getSelectedElement(selection);}
if(typeof(range)==="undefined"){var range=this._createRange(selection);}
var parentElement=range.commonAncestorContainer;if(parentElement.nodeType==9)return this._doc.body;while(parentElement&&parentElement.nodeType==3){parentElement=parentElement.parentNode;}
return parentElement;};HTMLArea.Editor.prototype._activeElement=function(selection){if(this._selectionEmpty(selection)){return null;}
if(selection.anchorNode.nodeType==1){return selection.anchorNode;}else{return null;}};HTMLArea.Editor.prototype._selectionEmpty=function(sel){if(!sel)return true;return sel.isCollapsed;};HTMLArea.Editor.prototype.getBookmark=function(range){var bookmark={startId:(new Date()).valueOf()+Math.floor(Math.random()*1000)+'S',endId:(new Date()).valueOf()+Math.floor(Math.random()*1000)+'E'};var startSpan;var endSpan;var rangeClone=range.cloneRange();if(!range.collapsed){endSpan=this._doc.createElement("span");endSpan.style.display="none";endSpan.id=bookmark.endId;endSpan.setAttribute("HTMLArea_bookmark",true);endSpan.innerHTML="&nbsp;";rangeClone.collapse(false);rangeClone.insertNode(endSpan);}
startSpan=this._doc.createElement("span");startSpan.style.display="none";startSpan.id=bookmark.startId;startSpan.setAttribute("HTMLArea_bookmark",true);startSpan.innerHTML="&nbsp;";var rangeClone=range.cloneRange();rangeClone.collapse(true);rangeClone.insertNode(startSpan);bookmark.startNode=startSpan;bookmark.endNode=endSpan;if(endSpan){range.setEndBefore(endSpan);range.setStartAfter(startSpan);}else{range.setEndAfter(startSpan);range.collapse(false);}
return bookmark;};HTMLArea.Editor.prototype.getBookmarkNode=function(bookmark,endPoint){if(endPoint){return this._doc.getElementById(bookmark.startId);}else{return this._doc.getElementById(bookmark.endId);}};HTMLArea.Editor.prototype.moveToBookmark=function(bookmark){var startSpan=this.getBookmarkNode(bookmark,true);var endSpan=this.getBookmarkNode(bookmark,false);var parent;var range=this._createRange();if(startSpan){if(startSpan.previousSibling&&startSpan.previousSibling.nodeType==3){range.setStart(startSpan.previousSibling,startSpan.previousSibling.data.length);}else{range.setStartBefore(startSpan);}
HTMLArea.removeFromParent(startSpan);}else{range.setStart(this._doc.body,0);}
if(endSpan){if(endSpan.nextSibling&&endSpan.nextSibling.nodeType==3){range.setEnd(endSpan.nextSibling,0);}else{range.setEndBefore(endSpan);}
HTMLArea.removeFromParent(endSpan);}else{range.collapse(true);}
return range;};HTMLArea.Editor.prototype.selectRange=function(range){var selection=this._getSelection();this.emptySelection(selection);this.addRangeToSelection(selection,range);};HTMLArea.Editor.prototype.insertNodeAtSelection=function(toBeInserted){this.focus();var range=this._createRange(this._getSelection());range.deleteContents();var toBeSelected=(toBeInserted.nodeType===11)?toBeInserted.lastChild:toBeInserted;range.insertNode(toBeInserted);this.selectNodeContents(toBeSelected,false);};HTMLArea.Editor.prototype.insertHTML=function(html){this.focus();var fragment=this._doc.createDocumentFragment();var div=this._doc.createElement("div");div.innerHTML=html;while(div.firstChild){fragment.appendChild(div.firstChild);}
this.insertNodeAtSelection(fragment);};HTMLArea.Editor.prototype.wrapWithInlineElement=function(element,selection,range){element.appendChild(range.extractContents());range.insertNode(element);element.normalize();var neighbour=element.previousSibling;if(neighbour&&(neighbour.nodeType!=3)&&!/\S/.test(neighbour.textContent)){HTMLArea.removeFromParent(neighbour);}
neighbour=element.nextSibling;if(neighbour&&(neighbour.nodeType!=3)&&!/\S/.test(neighbour.textContent)){HTMLArea.removeFromParent(neighbour);}
this.selectNodeContents(element,false);};HTMLArea.Editor.prototype.cleanAppleStyleSpans=function(node){if(Ext.isWebKit){if(node.getElementsByClassName){var spans=node.getElementsByClassName("Apple-style-span");for(var i=spans.length;--i>=0;){this.removeMarkup(spans[i]);}}else{var spans=node.getElementsByTagName("span");for(var i=spans.length;--i>=0;){if(HTMLArea.DOM.hasClass(spans[i],"Apple-style-span")){this.removeMarkup(spans[i]);}}
var fonts=node.getElementsByTagName("font");for(i=fonts.length;--i>=0;){if(HTMLArea.DOM.hasClass(fonts[i],"Apple-style-span")){this.removeMarkup(fonts[i]);}}}}};HTMLArea.Editor.prototype._checkBackspace=function(){var self=this;window.setTimeout(function(){var selection=self._getSelection();var range=self._createRange(selection);var startContainer=range.startContainer;var startOffset=range.startOffset;if(self._selectionEmpty()){if(/^(body)$/i.test(startContainer.nodeName)){var node=startContainer.childNodes[startOffset];}else if(/^(body)$/i.test(startContainer.parentNode.nodeName)){var node=startContainer;}else{return false;}
if(/^(br|#text)$/i.test(node.nodeName)&&!/\S/.test(node.textContent)){var previousSibling=node.previousSibling;while(previousSibling&&/^(br|#text)$/i.test(previousSibling.nodeName)&&!/\S/.test(previousSibling.textContent)){previousSibling=previousSibling.previousSibling;}
if(previousSibling){HTMLArea.removeFromParent(node);if(/^(ol|ul|dl)$/i.test(previousSibling.nodeName)){self.selectNodeContents(previousSibling.lastChild,false);}else if(/^(table)$/i.test(previousSibling.nodeName)){self.selectNodeContents(previousSibling.rows[previousSibling.rows.length-1].cells[previousSibling.rows[previousSibling.rows.length-1].cells.length-1],false);}else if(!/\S/.test(previousSibling.textContent)&&previousSibling.firstChild){self.selectNode(previousSibling.firstChild,true);}else{self.selectNodeContents(previousSibling,false);}}}}},10);return false;};HTMLArea.Editor.prototype._checkInsertP=function(){var editor=this;this.focus();var i,left,right,rangeClone,sel=this._getSelection(),range=this._createRange(sel),p=this.getAllAncestors(),block=null,a=null,doc=this._doc;for(i=0;i<p.length;++i){if(HTMLArea.isBlockElement(p[i])&&!/^(html|body|table|tbody|thead|tfoot|tr|dl)$/i.test(p[i].nodeName)){block=p[i];break;}}
if(block&&/^(td|th|tr|tbody|thead|tfoot|table)$/i.test(block.nodeName)&&this.config.buttons.table&&this.config.buttons.table.disableEnterParagraphs)return false;if(!range.collapsed){range.deleteContents();}
this.emptySelection(sel);if(!block||/^(td|div)$/i.test(block.nodeName)){if(!block){block=doc.body;}
if(block.hasChildNodes()){rangeClone=range.cloneRange();if(range.startContainer==block){var blockOnLeft=null;var leftSibling=null;for(var i=range.startOffset;--i>=0;){if(HTMLArea.isBlockElement(block.childNodes[i])){blockOnLeft=block.childNodes[i];break;}else{rangeClone.setStartBefore(block.childNodes[i]);}}}else{var inlineContainer=range.startContainer;while(inlineContainer.parentNode!=block){inlineContainer=inlineContainer.parentNode;}
var leftSibling=inlineContainer;while(leftSibling.previousSibling&&!HTMLArea.isBlockElement(leftSibling.previousSibling)){leftSibling=leftSibling.previousSibling;}
rangeClone.setStartBefore(leftSibling);var blockOnLeft=leftSibling.previousSibling;}
left=doc.createElement('p');left.appendChild(rangeClone.extractContents());if(!left.textContent&&!left.getElementsByTagName('img').length&&!left.getElementsByTagName('table').length){left.innerHTML='<br />';}
if(block.hasChildNodes()){if(blockOnLeft){left=block.insertBefore(left,blockOnLeft.nextSibling);}else{left=block.insertBefore(left,block.firstChild);}}else{left=block.appendChild(left);}
block.normalize();var rightSibling=left;while(rightSibling.nextSibling&&!HTMLArea.isBlockElement(rightSibling.nextSibling)){rightSibling=rightSibling.nextSibling;}
var blockOnRight=rightSibling.nextSibling;range.setEndAfter(rightSibling);range.setStartAfter(left);right=doc.createElement('p');right.appendChild(range.extractContents());if(!right.textContent&&!right.getElementsByTagName('img').length&&!right.getElementsByTagName('table').length){right.innerHTML='<br />';}
if(!(left.childNodes.length==1&&right.childNodes.length==1&&left.firstChild.nodeName.toLowerCase()=='br'&&right.firstChild.nodeName.toLowerCase()=='br')){if(blockOnRight){right=block.insertBefore(right,blockOnRight);}else{right=block.appendChild(right);}
this.selectNodeContents(right,true);}else{this.selectNodeContents(left,true);}
block.normalize();}else{var first=block.firstChild;if(first){block.removeChild(first);}
right=doc.createElement("p");if(Ext.isWebKit||Ext.isOpera){right.innerHTML="<br />";}
right=block.appendChild(right);this.selectNodeContents(right,true);}}else{range.setEndAfter(block);var df=range.extractContents(),left_empty=false;if(!/\S/.test(block.innerHTML)||(!/\S/.test(block.textContent)&&!/<(img|hr|table)/i.test(block.innerHTML))){if(!Ext.isOpera){block.innerHTML="<br />";}
left_empty=true;}
p=df.firstChild;if(p){if(!/\S/.test(p.innerHTML)||(!/\S/.test(p.textContent)&&!/<(img|hr|table)/i.test(p.innerHTML))){if(/^h[1-6]$/i.test(p.nodeName)){p=this.convertNode(p,"p");}
if(/^(dt|dd)$/i.test(p.nodeName)){p=this.convertNode(p,(p.nodeName.toLowerCase()==="dt")?"dd":"dt");}
if(!Ext.isOpera){p.innerHTML="<br />";}
if(/^li$/i.test(p.nodeName)&&left_empty&&(!block.nextSibling||!/^li$/i.test(block.nextSibling.nodeName))){left=block.parentNode;left.removeChild(block);range.setEndAfter(left);range.collapse(false);p=this.convertNode(p,/^(li|dd|td|th|p|h[1-6])$/i.test(left.parentNode.nodeName)?"br":"p");}}
range.insertNode(df);if(p.previousSibling){var a=p.previousSibling.lastChild;if(a&&/^a$/i.test(a.nodeName)&&!/\S/.test(a.innerHTML)){this.convertNode(a,'br');}}
var a=p.lastChild;if(a&&/^a$/i.test(a.nodeName)&&!/\S/.test(a.innerHTML)){this.convertNode(a,'br');}
while(p.firstChild&&p.firstChild.nodeType==1&&!/^(br|img|hr|table)$/i.test(p.firstChild.nodeName)){p=p.firstChild;}
if(/^br$/i.test(p.nodeName)){p=p.parentNode.insertBefore(doc.createTextNode('\x20'),p);}else if(!/\S/.test(p.innerHTML)){p.appendChild(doc.createElement('br'));}
this.selectNodeContents(p,true);}else{if(/^(li|dt|dd)$/i.test(block.nodeName)){p=doc.createElement(block.nodeName);}else{p=doc.createElement("p");}
if(!Ext.isOpera){p.innerHTML="<br />";}
if(block.nextSibling){p=block.parentNode.insertBefore(p,block.nextSibling);}else{p=block.parentNode.appendChild(p);}
this.selectNodeContents(p,true);}}
this.scrollToCaret();return true;};HTMLArea.Editor.prototype._detectURL=function(event){var ev=event.browserEvent;var editor=this;var s=this._getSelection();if(this.getParentElement(s).nodeName.toLowerCase()!='a'){var autoWrap=function(textNode,tag){var rightText=textNode.nextSibling;if(typeof(tag)=='string')tag=editor._doc.createElement(tag);var a=textNode.parentNode.insertBefore(tag,rightText);HTMLArea.removeFromParent(textNode);a.appendChild(textNode);s.collapse(rightText,0);rightText.parentNode.normalize();editor._unLink=function(){var t=a.firstChild;a.removeChild(t);a.parentNode.insertBefore(t,a);HTMLArea.removeFromParent(a);t.parentNode.normalize();editor._unLink=null;editor._unlinkOnUndo=false;};editor._unlinkOnUndo=true;return a;};switch(ev.which){case 13:case 32:if(s&&s.isCollapsed&&s.anchorNode.nodeType==3&&s.anchorNode.data.length>3&&s.anchorNode.data.indexOf('.')>=0){var midStart=s.anchorNode.data.substring(0,s.anchorOffset).search(/[a-zA-Z0-9]+\S{3,}$/);if(midStart==-1)break;if(this._getFirstAncestor(s,'a'))break;var matchData=s.anchorNode.data.substring(0,s.anchorOffset).replace(/^.*?(\S*)$/,'$1');if(matchData.indexOf('@')!=-1){var m=matchData.match(HTMLArea.RE_email);if(m){var leftText=s.anchorNode;var rightText=leftText.splitText(s.anchorOffset);var midText=leftText.splitText(midStart);var midEnd=midText.data.search(/[^a-zA-Z0-9\.@_\-]/);if(midEnd!=-1)var endText=midText.splitText(midEnd);autoWrap(midText,'a').href='mailto:'+m[0];break;}}
var m=matchData.match(HTMLArea.RE_url);if(m){var leftText=s.anchorNode;var rightText=leftText.splitText(s.anchorOffset);var midText=leftText.splitText(midStart);var midEnd=midText.data.search(/[^a-zA-Z0-9\._\-\/\&\?=:@]/);if(midEnd!=-1)var endText=midText.splitText(midEnd);autoWrap(midText,'a').href=(m[1]?m[1]:'http://')+m[3];break;}}
break;default:if(ev.keyCode==27||(editor._unlinkOnUndo&&ev.ctrlKey&&ev.which==122)){if(this._unLink){this._unLink();event.stopEvent();}
break;}else if(ev.which||ev.keyCode==8||ev.keyCode==46){this._unlinkOnUndo=false;if(s.anchorNode&&s.anchorNode.nodeType==3){var a=this._getFirstAncestor(s,'a');if(!a)break;if(!a._updateAnchTimeout){if(s.anchorNode.data.match(HTMLArea.RE_email)&&(a.href.match('mailto:'+s.anchorNode.data.trim()))){var textNode=s.anchorNode;var fn=function(){a.href='mailto:'+textNode.data.trim();a._updateAnchTimeout=setTimeout(fn,250);};a._updateAnchTimeout=setTimeout(fn,250);break;}
var m=s.anchorNode.data.match(HTMLArea.RE_url);if(m&&a.href.match(s.anchorNode.data.trim())){var textNode=s.anchorNode;var fn=function(){var m=textNode.data.match(HTMLArea.RE_url);a.href=(m[1]?m[1]:'http://')+m[3];a._updateAnchTimeout=setTimeout(fn,250);}
a._updateAnchTimeout=setTimeout(fn,250);}}}}
break;}}};